export {
  isNullOrUndefined,
  getYears,
  sleep,
  logOnDev,
  convertToRGBA,
  detectDeviceTypeAndOS,
  scrollToTop,
  scrollToTopNoneSmooth,
  generateRandomNumber,
  transformArrayToDictByKey,
  openPhoneApp,
  openSmsApp,
  openKakaoMap,
  openTMap,
  openNaverMap,
  copyToClipboard,
  isLightColor,
  getFormValues,
  deepEqual,
  openPopup,
} from './common-lib.ts';
